version: "3.7"
services:
  licensing-service:
    image: ostock/licnesing-service
    ports:
      - "8182:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_CLOUD_CONFIG_URI: "http://localhost:8181"